on:
  release:
    types: [created]
  workflow_dispatch:

name: Release MyApp

jobs:
#   delete_latest:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Delete the "latest" Release
#         uses: dev-drprasad/delete-tag-and-release@v0.2.1
#         with:
#           tag_name: latest
#           delete_release: true
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  release:
    strategy:
      matrix:
        goos: [darwin, linux, windows]
        goarch: [amd64, arm64]
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      repository-projects: write
    steps:
      - name: set goos
        run: echo "GOOS=${{ matrix.goos }}"
      - name: set goarch
        run: echo "GOARCH=${{ matrix.goarch }}"
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v3
        with:
          go-version: "1.21.0"
          check-latest: true
      - run: env GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} make build
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: "tar"
          directory: .
          filename: myapp-${{ matrix.goos }}.${{ matrix.goarch }}.tar.gz
          path: myapp*
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: myapp-${{ matrix.goos }}.${{ matrix.goarch }}.tar.gz
          asset_name: myapp-${{ matrix.goos }}.${{ matrix.goarch }}.tar.gz
          asset_content_type: application/gzip
      - name: Publish the Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: latest
          files: myapp-${{ matrix.goos }}.${{ matrix.goarch }}.tar.gz
          prerelease: true
          fail_on_unmatched_files: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
